image: maven:3-jdk-11

stages:
  - build
  - test
  - deploy

#compile:
#  stage: build
#  script:
#    - mvn -f pom.xml clean validate
#    - mvn -f pom.xml clean compile 
    
#junit-test:
# stage: test
#  script:
#    - mvn -f pom.xml clean test
#  artifacts:
#    paths:
#      - target/surefire-reports/TEST-*.xml
#    reports:
#      junit:
#        - target/surefire-reports/TEST-*.xml

create-jar:
  stage: deploy
  script:
    - mvn -f pom.xml clean package
    - mv target/CCN.jar /builds/e16/courses/software-development/ss22/group04_coop/collaborative-carrier-network/
    - git add target/CCN.jar
    - git commit -m "add jar"
    - git push -f

